plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}
group = 'com.ourcommunity'
version = '0.0.1-SNAPSHOT'
java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}
repositories { mavenCentral() }
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.0'
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.apache.poi:poi-ooxml:5.5.1'
    // Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-websocket
    implementation 'org.springframework.boot:spring-boot-websocket:4.1.0'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
}
tasks.register('preparePasswordHash', Copy) {
    dependsOn classes
    from configurations.runtimeClasspath
    into layout.buildDirectory.dir('password-hash-libs')
}
